# Generated by Django 5.2.3 on 2025-07-01 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('icon', models.CharField(max_length=50, verbose_name='Ícone')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Pontos')),
                ('requirement_type', models.CharField(choices=[('adventures_completed', 'Aventuras Completadas'), ('points_earned', 'Pontos Acumulados'), ('specific_adventure', 'Aventura Específica'), ('payment_method', 'Método de Pagamento')], max_length=50, verbose_name='Tipo de Requisito')),
                ('requirement_value', models.JSONField(default=dict, help_text='Configuração específica do requisito em formato JSON', verbose_name='Valor do Requisito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insígnia',
                'verbose_name_plural': 'Insígnias',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('icon', models.CharField(max_length=50, verbose_name='Ícone')),
                ('points_cost', models.PositiveIntegerField(verbose_name='Custo em Pontos')),
                ('reward_type', models.CharField(choices=[('discount', 'Desconto'), ('free_adventure', 'Aventura Grátis'), ('merchandise', 'Brinde')], max_length=50, verbose_name='Tipo de Recompensa')),
                ('value', models.JSONField(default=dict, help_text='Configuração específica da recompensa em formato JSON', verbose_name='Valor da Recompensa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='adventurer_level',
            field=models.CharField(choices=[('iniciante_trilha', 'Iniciante de Trilha'), ('explorador_selva', 'Explorador de Selva'), ('guerreiro_alturas', 'Guerreiro das Alturas'), ('mestre_aventuras', 'Mestre das Aventuras')], default='iniciante_trilha', max_length=50, verbose_name='Nível do Aventureiro'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='available_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Pontos Disponíveis'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level_progress',
            field=models.PositiveIntegerField(default=0, help_text='Porcentagem de progresso para o próximo nível (0-100)', verbose_name='Progresso do Nível'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de Pontos'),
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('used', 'Utilizado'), ('expired', 'Expirado')], default='pending', max_length=20)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recompensa do Usuário',
                'verbose_name_plural': 'Recompensas dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insígnia do Usuário',
                'verbose_name_plural': 'Insígnias dos Usuários',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
