# Generated by Django 5.2.3 on 2025-06-28 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vídeo'), ('image', 'Imagem'), ('document', 'Documento'), ('presentation', 'Apresentação'), ('link', 'Link Externo')], max_length=20, verbose_name='Tipo de Arquivo')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'mp4', 'webm', 'avi', 'mov', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'rar', '7z'])], verbose_name='Arquivo')),
                ('external_url', models.URLField(blank=True, help_text='Para vídeos do YouTube, links externos, etc.', verbose_name='URL Externa')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='materials/thumbnails/', verbose_name='Thumbnail/Preview')),
                ('access_level', models.CharField(choices=[('public', 'Público'), ('registered', 'Usuários Registrados'), ('premium', 'Premium')], default='registered', max_length=20, verbose_name='Nível de Acesso')),
                ('requires_registration', models.BooleanField(default=True, verbose_name='Requer Cadastro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacar')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho do Arquivo (bytes)')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Contagem de Downloads')),
                ('tags', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula para facilitar a busca', max_length=500, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material de Apoio',
                'verbose_name_plural': 'Materiais de Apoio',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Acesso a Material',
                'verbose_name_plural': 'Acessos a Materiais',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, help_text='Classe CSS do ícone FontAwesome (ex: fas fa-file-pdf)', max_length=50, verbose_name='Ícone')),
                ('color', models.CharField(default='#007bff', help_text='Cor hexadecimal para representar a categoria', max_length=7, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Material',
                'verbose_name_plural': 'Categorias de Materiais',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name='Nome do Visitante')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Visitante')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Download de Material',
                'verbose_name_plural': 'Downloads de Materiais',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
