# Generated by Django 5.2.3 on 2025-06-28 17:44

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_description', models.CharField(help_text='Descrição que aparece na listagem de aventuras', max_length=300, verbose_name='Descrição Curta')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descrição Completa')),
                ('difficulty', models.CharField(choices=[('iniciante', 'Iniciante'), ('moderado', 'Moderado'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('expert', 'Expert')], max_length=20, verbose_name='Nível de Dificuldade')),
                ('duration_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)], verbose_name='Duração (horas)')),
                ('min_participants', models.PositiveIntegerField(default=4, verbose_name='Mínimo de Participantes')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='Máximo de Participantes')),
                ('location', models.CharField(max_length=200, verbose_name='Localização')),
                ('meeting_point', models.TextField(verbose_name='Ponto de Encontro')),
                ('coordinates_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('coordinates_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Base')),
                ('what_includes', ckeditor.fields.RichTextField(help_text='Liste tudo que está incluído na aventura', verbose_name='O que está incluído')),
                ('what_to_bring', ckeditor.fields.RichTextField(help_text='Lista do que o participante deve levar', verbose_name='O que levar')),
                ('safety_requirements', ckeditor.fields.RichTextField(help_text='Informações importantes sobre segurança', verbose_name='Requisitos de Segurança')),
                ('additional_info', ckeditor.fields.RichTextField(blank=True, verbose_name='Informações Adicionais')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacar na Home Page')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('show_in_listing', models.BooleanField(default=True, verbose_name='Exibir na Listagem')),
                ('main_image', models.ImageField(upload_to='adventures/main/', verbose_name='Imagem Principal')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta Título')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aventura',
                'verbose_name_plural': 'Aventuras',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, help_text='Classe CSS do ícone FontAwesome (ex: fas fa-mountain)', max_length=50, verbose_name='Ícone')),
                ('color', models.CharField(default='#007bff', help_text='Cor hexadecimal para representar a categoria', max_length=7, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdventureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='adventures/gallery/', verbose_name='Imagem')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Imagem de Capa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adventures.adventure', verbose_name='Aventura')),
            ],
            options={
                'verbose_name': 'Imagem da Aventura',
                'verbose_name_plural': 'Imagens da Aventura',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adventure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to='adventures.category', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Promoção Antecipada, Preço Normal, Última Hora', max_length=100, verbose_name='Nome do Período')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(verbose_name='Data de Fim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual em relação ao preço base', max_digits=5, null=True, verbose_name='Percentual de Desconto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='adventures.adventure', verbose_name='Aventura')),
            ],
            options={
                'verbose_name': 'Faixa de Preço',
                'verbose_name_plural': 'Faixas de Preço',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='adventures.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'ordering': ['order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='adventure',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adventures', to='adventures.subcategory', verbose_name='Subcategoria'),
        ),
    ]
