# Generated by Django 5.2.3 on 2025-06-28 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Participantes')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total')),
                ('status', models.CharField(choices=[('pending', 'Aguardando Aprovação'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('completed', 'Concluído')], default='pending', max_length=20, verbose_name='Status da Reserva')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('partial', 'Parcial'), ('paid', 'Pago'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Status do Pagamento')),
                ('user_notes', models.TextField(blank=True, help_text='Comentários ou solicitações especiais', verbose_name='Observações do Usuário')),
                ('admin_notes', models.TextField(blank=True, help_text='Notas internas para a equipe', verbose_name='Observações da Administração')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Contato de Emergência')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Emergência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('document_type', models.CharField(choices=[('waiver', 'Termo de Responsabilidade'), ('insurance', 'Documento de Seguro'), ('checklist', 'Checklist'), ('instructions', 'Instruções'), ('map', 'Mapa/Localização'), ('other', 'Outro')], max_length=20, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='event_documents/', verbose_name='Arquivo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_required_reading', models.BooleanField(default=False, verbose_name='Leitura Obrigatória')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento do Evento',
                'verbose_name_plural': 'Documentos dos Eventos',
                'ordering': ['-is_required_reading', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company', models.CharField(max_length=200, verbose_name='Seguradora')),
                ('policy_number', models.CharField(max_length=100, verbose_name='Número da Apólice')),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Cobertura')),
                ('coverage_details', models.TextField(verbose_name='Detalhes da Cobertura')),
                ('exclusions', models.TextField(blank=True, verbose_name='Exclusões')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Telefone da Seguradora')),
                ('emergency_contact', models.CharField(max_length=20, verbose_name='Contato de Emergência')),
                ('valid_from', models.DateField(verbose_name='Válido de')),
                ('valid_until', models.DateField(verbose_name='Válido até')),
                ('additional_info', models.TextField(blank=True, verbose_name='Informações Adicionais')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informação de Seguro',
                'verbose_name_plural': 'Informações de Seguro',
            },
        ),
        migrations.CreateModel(
            name='UserChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Marcado')),
                ('notes', models.TextField(blank=True, help_text='Observações pessoais sobre este item', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checklist do Usuário',
                'verbose_name_plural': 'Checklists dos Usuários',
                'ordering': ['checklist_item__order', 'checklist_item__item_name'],
            },
        ),
        migrations.CreateModel(
            name='AdventureChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Item')),
                ('item_type', models.CharField(choices=[('equipment', 'Equipamento'), ('clothing', 'Vestuário'), ('food', 'Alimentação'), ('document', 'Documento'), ('personal', 'Item Pessoal'), ('medical', 'Médico/Saúde')], max_length=20, verbose_name='Tipo de Item')),
                ('description', models.TextField(blank=True, help_text='Detalhes ou especificações do item', verbose_name='Descrição')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('is_provided', models.BooleanField(default=False, verbose_name='Fornecido pela empresa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='adventures.adventure', verbose_name='Aventura')),
            ],
            options={
                'verbose_name': 'Item do Checklist',
                'verbose_name_plural': 'Itens do Checklist',
                'ordering': ['adventure', 'item_type', 'order', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='AdventureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Horário de Início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Término')),
                ('max_participants', models.PositiveIntegerField(verbose_name='Máximo de Participantes')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Participantes Atuais')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco para usar o preço da aventura', max_digits=10, null=True, verbose_name='Preço Personalizado')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('completed', 'Concluído')], default='scheduled', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Prazo para Inscrições')),
                ('meeting_instructions', models.TextField(blank=True, help_text='Instruções específicas para este evento', verbose_name='Instruções de Encontro')),
                ('special_notes', models.TextField(blank=True, verbose_name='Observações Especiais')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='adventures.adventure', verbose_name='Aventura')),
            ],
            options={
                'verbose_name': 'Evento de Aventura',
                'verbose_name_plural': 'Eventos de Aventuras',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
