# Generated by Django 5.2.3 on 2025-06-28 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0001_initial'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='booking',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.adventureevent', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='eventdocument',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bookings.adventureevent', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='insuranceinfo',
            name='adventure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_info', to='adventures.adventure', verbose_name='Aventura'),
        ),
        migrations.AddField(
            model_name='userchecklist',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_checklist', to='bookings.booking', verbose_name='Reserva'),
        ),
        migrations.AddField(
            model_name='userchecklist',
            name='checklist_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.adventurechecklist', verbose_name='Item do Checklist'),
        ),
        migrations.AlterUniqueTogether(
            name='adventureevent',
            unique_together={('adventure', 'date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='userchecklist',
            unique_together={('booking', 'checklist_item')},
        ),
    ]
