# Generated by Django 5.2.3 on 2025-06-30 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Cartão de Crédito'), ('pix', 'PIX'), ('bank_transfer', 'Transferência Bancária'), ('cash', 'Dinheiro')], max_length=20, verbose_name='Método de Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('installments', models.PositiveIntegerField(default=1, verbose_name='Parcelas')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('external_payment_id', models.CharField(blank=True, max_length=200, verbose_name='ID do Pagamento Externo')),
                ('pix_key', models.CharField(blank=True, max_length=200, verbose_name='Chave PIX')),
                ('pix_qr_code', models.TextField(blank=True, verbose_name='QR Code PIX')),
                ('payment_data', models.JSONField(blank=True, default=dict, verbose_name='Dados do Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('emergency_contact_name', models.CharField(max_length=100, verbose_name='Nome do Contato de Emergência')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='Telefone do Contato de Emergência')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=10, verbose_name='CEP')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='Condições Médicas')),
                ('medications', models.TextField(blank=True, verbose_name='Medicamentos')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('status', models.CharField(choices=[('pending', 'Aguardando Análise'), ('approved', 'Aprovado - Pode Pagar'), ('rejected', 'Rejeitado'), ('converted', 'Convertido em Inscrição')], default='pending', max_length=20, verbose_name='Status')),
                ('user_notes', models.TextField(blank=True, verbose_name='Observações do Cliente')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Observações da Administração')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Criado')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_registrations', to='bookings.adventureevent', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Pré-inscrição',
                'verbose_name_plural': 'Pré-inscrições',
                'ordering': ['-created_at'],
                'unique_together': {('cpf', 'event')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número do Telefone')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Nome do Destinatário')),
                ('message_type', models.CharField(choices=[('pre_registration', 'Pré-inscrição'), ('registration_confirmed', 'Inscrição Confirmada'), ('payment_confirmed', 'Pagamento Confirmado'), ('event_reminder', 'Lembrete do Evento'), ('cancellation', 'Cancelamento')], max_length=30, verbose_name='Tipo da Mensagem')),
                ('message_text', models.TextField(verbose_name='Texto da Mensagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('delivered', 'Entregue'), ('read', 'Lido'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='bookings.booking', verbose_name='Reserva')),
                ('pre_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='bookings.preregistration', verbose_name='Pré-inscrição')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
